version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - cd site && npm install
  build:
    commands:
      - npm run build --production
  post_build:
    commands:
      - rm -rf node_modules
      - rm -rf src
      - rm -rf public

artifacts:
  files:
    - '**/*'
