version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - env
  build:
    commands:
      - go mod download
      - GOARCH=amd64 GOOS=linux go build -o application application.go
      - ls

artifacts:
  files:
    - "**/*"
