version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - env
  build:
    commands:
      - cd site && npm run build
  post-build:
    commands:
      - ls
      - cd site && rm -rf node_modules

artifacts:
  files:
    - '**/*'
