version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - env
  build:
    commands:
      - go mod download
      - go build -o bin/application.go application.go
      - ls
